services:
  mongo:
    image: mongo
    container_name: Bucketlist_mongodb
    restart: always
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    restart: always
    container_name: Bucketlist_redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  s3:
    image: minio/minio
    container_name: Bucketlist_minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build: ./API
    container_name: Bucketlist_API
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - s3
    environment:
      MONGO_URI: mongodb://root:password@mongodb:27017/Bucketlist?authSource=admin
      S3_ENDPOINT: http://s3:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin

volumes:
  mongo_data:
  minio_data:
  redis-data:
